version: '3'

services:
# Un-comment this service if you want to run api mock in a container and not natively
#  api-mock:
#    container_name: api-mock
#    build:
#      context: ../api-mock
#    ports:
#      - "8023:8023"
#    volumes:
#      - /app/data/api-mock
  postgres:
      image: postgres:latest
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - .env
      ports:
        - "5434:5432"

  keycloak:
      build:
        context: .
      env_file:
        - .env
      ports:
        - "8083:8080"
      depends_on:
        - postgres
      # Flags useful during themes development --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
      entrypoint: /opt/keycloak/bin/kc.sh start-dev

volumes:
  postgres_data:
