version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:latest
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      env_file:
        - .env
      ports:
        - "5434:5432"
  keycloak:
      build:
        context: .
      env_file:
        - .env
      volumes:
        - ./theme/:/opt/keycloak/themes/
        - ./realm:/opt/keycloak/data/import
      ports:
        - "8083:8080"
        - "8789:8787"
      depends_on:
        - postgres
      entrypoint: /opt/keycloak/bin/kc.sh start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --import-realm
